### ISSUE TITLE
add a preferences change handler

### ISSUE THREAD

**Issue by zaggino** [brad-jones/git-projects#1]
it should be possible to use `prefs.on(...)` change handler to watch for changes to the `"git-projects.maxDepth"` and rescan the directories when changed (so people don't have to restart the brackets)

ref: https://github.com/adobe/brackets/blob/master/src/preferences/PreferencesBase.js#L1131-L1152

**Comment by brad-jones** [comment]
Thanks zaggino I'll take a look next time I do some work on the plugin.

**Comment by zaggino** [comment]
Sure, nice work btw ;)
