### ISSUE TITLE
Brackets for WIN7: Extension blocks everything on startup...

### ISSUE THREAD

**Issue by 3und60** [brad-jones/git-projects#2]
Hi Brad,

I have problems with Git Projects installed on Brackets on WIN7 n application start up as I described yesterday here:

https://github.com/adobe/brackets/issues/10636

As I already described, a complete reinstall does not help. %appdata% or a roaming folder for manually wipe it away does not exist either.

"peterflynn" recommended to contact you if his hint doesn't help. Can you please?

Cheers Thomas

**Comment by brad-jones** [comment]
Hi Thomas,

Sorry about that, seems I have caused you some grief.

To be honest I have not used and tested my extension on any other platform but linux.
And even then I am running the latest 1.2 build, which isn't released yet.

It will probably be to do with the differences between unix and windows paths.
Or just my lack of understanding of the brackets API. I think I spent about 2 hours
hacking the plugin together a couple of days ago.

I am busy again working on paying project but when I get some time
I'll take a look and test it out more thoroughly across the different platforms.
Or feel free to send me a pull request if you have a fix for me.

Cheers Brad

**Comment by 3und60** [comment]
Hi Brad,

Thanks for the quick reply.

Just to underline again: The application "Brackets" is DEAD on my machine!! Its not only the case that the extension is not working, the whole app is broken, because, as I said, at startup the extension wants a path I can't provide and there is no way around it like a "cancel" button or so. So since uninstall and re-install of brackets does not work as well ( I assumed that all the functionality will be removed as well with the uninstall, but its not the case ) I am sitting here a bit confused. Do you have a quick workaround to at least get back on track with the rest of the functionality of brackets?

Thank you!

Cheers Thomas

**Comment by brad-jones** [comment]
Hi Thomas,

As I have never used brackets on a windows based OS yet. I can only take a guess.

Simply Un-installing Brackets probably does not remove your Brackets User Data.
On a *NIX operating system this would usually be found at: `/home/USERNAME/.config/brackets`
On Windows I would look in your AppData directory for the equivalent folder.

> Here is more info about AppData: http://windows.microsoft.com/en-au/windows-8/what-appdata-folder

All brackets "USER INSTALLED" extensions will be found in this folder where ever it is on a windows pc. All you need to do is delete the "git-projects" extension. And then your brackets instance should fire up hopefully.

If all else fails search your hard drive for "git-projects" and delete all found files and folders.
Maybe take a backup though...

Cheers Brad

**Comment by 3und60** [comment]
Thanks again. I'll give it a try. Although I already searched the registry and the users folder but haven't found things so far. But I will report on that soon as well.

Cheers Thomas

**Comment by peterflynn** [comment]
@3und60 Please see my response in the Brackets bug. You can always manually uninstall or disable the extension -- see https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually.

**Comment by 3und60** [comment]
Just to let you know: I deleted the folder of the extension, which was hidden somehow. And secondly all extensions of Brackets still exist although I completely uninstalled Brackets. Anyway. After this I can work with brackets again. But still this is an issue, because the extension causing a complete block of the application under WIN7/WIN8. So this should be corrected. Thank you.
