### ISSUE TITLE
conflicts with Navigate > Go to Line

### ISSUE THREAD

**Issue by zaggino** [brad-jones/git-projects#4]
Whenever I open `Navigate > Go to Line` by mouse or by shortcut `cmd+L` I get git-projects instead of standard functionality. Might be or not be Mac only issue.

**Comment by brad-jones** [comment]
Really odd, I can confirm though it is doing the same thing for me on Linux.
I think it is something to do with how I have implemented the Quick Open Plugin.
As the keyboard short cut for Got To Line for me is Ctrl+G so it's not a key binding conflict as I straight away assumed.
Anyway will have a look.
